server:
  port: 8081
# Redis 配置
# Redis数据库索引（默认为0）
spring:
  redis:
    database: 1
# Redis服务器地址
    host: 127.0.0.1
# Redis服务器连接端口
    port: 6379
# Redis服务器连接密码
    password: ccenrun123
# 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 100
# 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: 5000
# 连接池中的最大空闲连接
      max-idle: 10
# 连接池中的最小空闲连接
      min-idle: 0